version: '{build}'

environment:
  matrix:
  - job_name: Windows build
    appveyor_build_worker_image: Visual Studio 2019
  - job_name: Linux build
    appveyor_build_worker_image: Ubuntu
  - job_name: macOS build
    appveyor_build_worker_image: macos
  global:
    SIGN_BUILD: false

cache:
  - node_modules -> package.json
  - app\node_modules -> app\package.json

for:

  -
    matrix:
      only:
        - job_name: Linux build

    build_script:
    - sh: npm run lint
    - sh: npm run postinstall
    - sh: DEBUG=electron-packager,electron-osx-sign npm run build

    after_build:
    - sh: ./scripts/deploy.sh

  -
   matrix:
     only:
       - job_name: macOS build

   build_script:
   - sh: npm run lint
   - sh: npm run postinstall
   - sh: DEBUG=electron-packager,electron-osx-sign npm run build

   after_build:
   - sh: ./scripts/deploy.sh

  -
    matrix:
      only:
        - job_name: Windows build

    init:
    - ps: $env:commit = $env:appveyor_repo_commit.SubString(0,8)

    install:
    - ps: Install-Product node 11
    - ps: npm config set msvs_version 2015


    build_script:
    - cmd: npm install && npm run build
    - cmd: node app/build/create-windows-installer.js

    after_build:
    - ps: Get-ChildItem .\app\dist\*.tar.gz | % { Push-AppveyorArtifact $_.FullName -FileName "$($_.Name)" }
    - ps: Get-ChildItem .\app\dist\MailspringSetup.exe | % { Push-AppveyorArtifact $_.FullName -FileName "$($_.Name)" }
    - ps: Get-ChildItem .\app\dist\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName "$($_.Name)" }
    - ps: Get-ChildItem .\app\dist\RELEASES | % { Push-AppveyorArtifact $_.FullName -FileName "$($_.Name)" }


# Stop Appveyor from "Discovering Tests" forever
test: off
